// <auto-generated />
using JoshuaAllison_TermProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JoshuaAllison_TermProject.Migrations
{
    [DbContext(typeof(DS3ItemContext))]
    [Migration("20211208235316_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackType")
                        .HasColumnType("int");

                    b.Property<int>("AuxType")
                        .HasColumnType("int");

                    b.Property<int>("AuxValue")
                        .HasColumnType("int");

                    b.Property<int>("Critical")
                        .HasColumnType("int");

                    b.Property<int>("DarkAR")
                        .HasColumnType("int");

                    b.Property<int>("DarkDR")
                        .HasColumnType("int");

                    b.Property<int>("DexterityRequirement")
                        .HasColumnType("int");

                    b.Property<string>("DexterityScaling")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("FPConsumption")
                        .HasColumnType("int");

                    b.Property<int>("FaithRequirement")
                        .HasColumnType("int");

                    b.Property<string>("FaithScaling")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("FireAR")
                        .HasColumnType("int");

                    b.Property<int>("FireDR")
                        .HasColumnType("int");

                    b.Property<string>("IconURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntellectRequirement")
                        .HasColumnType("int");

                    b.Property<string>("IntellectScaling")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("LightningAR")
                        .HasColumnType("int");

                    b.Property<int>("LightningDR")
                        .HasColumnType("int");

                    b.Property<int>("MagicAR")
                        .HasColumnType("int");

                    b.Property<int>("MagicDR")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysicalAR")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDR")
                        .HasColumnType("int");

                    b.Property<int>("Stability")
                        .HasColumnType("int");

                    b.Property<int>("StrengthRequirement")
                        .HasColumnType("int");

                    b.Property<string>("StrengthScaling")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponArtId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("EquipmentId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("WeaponArtId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.Subcategory", b =>
                {
                    b.Property<int>("SubcategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            SubcategoryId = 1,
                            Category = 0,
                            Description = "Katanas are a type of Weapon in Dark Souls 3. These Weapons usually do moderate to good damage and deal Bleed. These weapons have particularly strong running attacks. Like curved swords, they're utilized primarily for slashing attacks. While useful in many scenarios, their main downfall is their low durability (an issue that is easily solved in this game, due how durability works), and really low STR scaling (gaining almost no damage benefit from using them two handed).",
                            SubcategoryName = "Katanas"
                        },
                        new
                        {
                            SubcategoryId = 2,
                            Category = 0,
                            Description = @"Fist & Claws are a type of Weapon in Dark Souls 3. These Weapons usually have similar movesets albeit with different skills and properties. Fists and Claws are often used as parrying tools, due to their fast parry frames.
Fists:	Fist weapons have a faster light attack than Claws and a different rolling R1, but have shorter range and lack the innate Bleed Auxiliary effect that Claws have.Fist weapons are mostly used for Quality / Strength builds and due to their higher damage and considerably better Weapon Arts, they are usually favored over Claws.
Claws:	Claws have a slightly slower light attack than Fist weapons but have considerably different movesets when two handed(the Crow Talons especially).Claws have greater range than the Fists and have innate Bleed.Claws are usually used on Dexterity / Luck builds.",
                            SubcategoryName = "Fist & Claws"
                        },
                        new
                        {
                            SubcategoryId = 3,
                            Category = 0,
                            Description = @"Halberds are a type of Weapon in Dark Souls 3. These Weapons usually do moderate damage and have long reach. Halberds are generally either a fusion between a spear and another weapon, thus combining straight thrusting attacks and wide swinging strikes, or are simply a cutting or chopping weapon on a long shaft, which is swung across and overhead at a distance. These weapons often have trouble performing in close range or tight quarters.
Just like Reapers, they have a ""sweet spot"" mechanic that awards players extra damage. Even though the sour spots return as well, the damage difference between the sweet spot hit and the sour spot hit isn't as harsh.",
                            SubcategoryName = "Halberds"
                        },
                        new
                        {
                            SubcategoryId = 4,
                            Category = 0,
                            Description = "Whips are a type of Weapon in Dark Souls 3. These Weapons usually do little to moderate damage, and perform poorly against well-armored foes, but have long reach and can have Auxiliary effects such as Bleeding or Poison. Unlike other melee weapons, whips cannot be parried but cannot backstab or riposte.",
                            SubcategoryName = "Whips"
                        },
                        new
                        {
                            SubcategoryId = 5,
                            Category = 0,
                            Description = @"Greatswords are a high damage, long reach weapon class. Plan to put a decent amount of points into Strength if you plan to use these weapons. They have various weapon Skills ranging from Stomp to Stance to unique Skills.
In terms of damage output per stamina expended, Greatswords are easily the best value weapon category, and they are a good choice for PvE builds as a result.Things to keep in mind when using these in PvP:
	 1. They have less range compared to Spears / Halberds, Greataxes, and Ultra Greatswords.
	 2. The startup to their attacks is markedly slower compared to Straight Swords, Axes, and other smaller weapons.
	 3. Despite the visual being a thrusting attack, the weapon art heavy deals standard damage(slash for the Flamberge) unless the Greatsword has a thrusting neutral heavy.",
                            SubcategoryName = "Greatswords"
                        },
                        new
                        {
                            SubcategoryId = 6,
                            Category = 1,
                            Description = "Small Shields  in Dark Souls 3 are a type of Shield that usually weigh very little and have the least form of protection from attacks. They are often used by players who prefer Parrying rather than Blocking.",
                            SubcategoryName = "Small Shields"
                        },
                        new
                        {
                            SubcategoryId = 7,
                            Category = 1,
                            Description = "Shields in Dark Souls III are an integral part of survival as you begin to understand enemy mechanics. As they are more than just a barrier used to distance yourself from imminent attacks, shields are widely avaiable in various sizes which allow a player to mesh their main-hand weapons into a personalized playstyle. With offensive applications in addition to their apparent defensive application, strategic use of the shield allows for more than simple damage reduction.",
                            SubcategoryName = "Standard Shields"
                        },
                        new
                        {
                            SubcategoryId = 8,
                            Category = 1,
                            Description = "Great Shields are a class of Shields in Dark Souls 3. These types of Shields usually weigh a decent amount and provide the best protection in the game. They are often used by players who have high Strength, as they require a good amount to use.",
                            SubcategoryName = "Greatshields"
                        });
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.WeaponArt", b =>
                {
                    b.Property<int>("WeaponArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponArtId");

                    b.ToTable("WeaponArts");

                    b.HasData(
                        new
                        {
                            WeaponArtId = 1,
                            Description = "While in stance, use normal attack to break a foe's guard from below, and strong attack to slash upwards with a forward lunge.",
                            Name = "Stance"
                        },
                        new
                        {
                            WeaponArtId = 2,
                            Description = "Cross arms in front of body to temporarily boost poise. Damage reduced while activated.",
                            Name = "Perseverance"
                        },
                        new
                        {
                            WeaponArtId = 3,
                            Description = "Spin weapon vigorously above head and sweep foes, and transition with normal or strong attack for continued spin attacks, which whip up wind and gain momentum, strengthening subsequent attacks.",
                            Name = "Wind Wheel"
                        },
                        new
                        {
                            WeaponArtId = 4,
                            Description = "Strike from the left to evade shields and deal a stinging blow that temporarily slows stamina recovery. The shackles of bondage lie deep in the hearts of all humankind.",
                            Name = "Impact"
                        },
                        new
                        {
                            WeaponArtId = 5,
                            Description = "Assume a holding stance to rapidly execute a lunging slash with normal attack, or a deflective parry with strong attack.",
                            Name = "Hold"
                        },
                        new
                        {
                            WeaponArtId = 6,
                            Description = "Without lowering your guard, strike the enemy with the shield to knock them back or stagger them. Works while equipped in either hand.",
                            Name = "Shield Bash"
                        },
                        new
                        {
                            WeaponArtId = 7,
                            Description = "Equipping this shield in the left hand allows one to perform the Skill of the right hand weapon.",
                            Name = "Weapon Skill"
                        },
                        new
                        {
                            WeaponArtId = 8,
                            Description = "Repel an attack at the right time to follow up with a critical hit.  Works while equipped in either hand.",
                            Name = "Parry"
                        },
                        new
                        {
                            WeaponArtId = 9,
                            Description = "Repel an attack at the right time to follow up with a critical hit.  Works while equipped in either hand.  Also deflects spells.",
                            Name = "Spell Parry"
                        },
                        new
                        {
                            WeaponArtId = 11,
                            Description = "Repel an attack at the right time to follow up with a critical hit.  Works while equipped in either hand.  Also deflects spells.",
                            Name = "Spell Parry"
                        });
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.Equipment", b =>
                {
                    b.HasOne("JoshuaAllison_TermProject.Models.Subcategory", "subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoshuaAllison_TermProject.Models.WeaponArt", "weaponArt")
                        .WithMany()
                        .HasForeignKey("WeaponArtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
