// <auto-generated />
using JoshuaAllison_TermProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JoshuaAllison_TermProject.Migrations
{
    [DbContext(typeof(DS3ItemContext))]
    [Migration("20211210201126_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.AuxillaryEffect", b =>
                {
                    b.Property<string>("AuxillaryEffectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuxillaryEffectId");

                    b.ToTable("AuxillaryEffects");

                    b.HasData(
                        new
                        {
                            AuxillaryEffectId = "N",
                            Description = "This item does not have an auxillary status effect.",
                            IconURL = "https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/icon_weight.png",
                            Name = "None"
                        },
                        new
                        {
                            AuxillaryEffectId = "B",
                            Description = "15% HP damage plus an additional 50-200 flat damage, varies by source",
                            IconURL = "https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/icon-bleedres.png",
                            Name = "Bleed"
                        },
                        new
                        {
                            AuxillaryEffectId = "F",
                            Description = "Inflicts damage, lower absorption, and slows stamina regeneration. Deals 11% of a player's max HP plus an additional 85 flat damage. When affected, the target has - 15 Stamina Regen and takes + 7 % increased damage.",
                            IconURL = "https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/icon-wp_frost.png",
                            Name = "Frostbite"
                        },
                        new
                        {
                            AuxillaryEffectId = "P",
                            Description = "Slowly inflicts HP damage on the player. Lasts for 90 Seconds, or until cured. ",
                            IconURL = "https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/icon-poisonres.png",
                            Name = "Poison"
                        });
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AuxEffectValue")
                        .HasColumnType("int");

                    b.Property<string>("AuxillaryEffectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Critical")
                        .HasColumnType("int");

                    b.Property<int>("DarkAR")
                        .HasColumnType("int");

                    b.Property<int>("DarkDR")
                        .HasColumnType("int");

                    b.Property<int>("DexterityRequirement")
                        .HasColumnType("int");

                    b.Property<string>("DexterityScaling")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("FPConsumption")
                        .HasColumnType("int");

                    b.Property<int>("FaithRequirement")
                        .HasColumnType("int");

                    b.Property<string>("FaithScaling")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("FireAR")
                        .HasColumnType("int");

                    b.Property<int>("FireDR")
                        .HasColumnType("int");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntellectRequirement")
                        .HasColumnType("int");

                    b.Property<string>("IntellectScaling")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ItemSubcategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LightningAR")
                        .HasColumnType("int");

                    b.Property<int>("LightningDR")
                        .HasColumnType("int");

                    b.Property<int>("MagicAR")
                        .HasColumnType("int");

                    b.Property<int>("MagicDR")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysicalAR")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDR")
                        .HasColumnType("int");

                    b.Property<int>("Stability")
                        .HasColumnType("int");

                    b.Property<int>("StrengthRequirement")
                        .HasColumnType("int");

                    b.Property<string>("StrengthScaling")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("WeaponArtId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("EquipmentId");

                    b.HasIndex("AuxillaryEffectId");

                    b.HasIndex("ItemSubcategoryId");

                    b.HasIndex("WeaponArtId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            AttackType = "Slash",
                            AuxEffectValue = 36,
                            AuxillaryEffectId = "B",
                            Critical = 100,
                            DarkAR = 0,
                            DarkDR = 35,
                            DexterityRequirement = 14,
                            DexterityScaling = "D",
                            Durability = 70,
                            FPConsumption = 18,
                            FaithRequirement = 0,
                            FaithScaling = "-",
                            FireAR = 0,
                            FireDR = 30,
                            FlavorText = "Greatsword with an undulating blade. The blade, resembling flame, was crafted to mutilate flesh and induce bleeding.",
                            IconURL = "https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/flameberge.png",
                            IntellectRequirement = 0,
                            IntellectScaling = "-",
                            ItemSubcategoryId = "GS",
                            LightningAR = 0,
                            LightningDR = 30,
                            MagicAR = 0,
                            MagicDR = 35,
                            Name = "Flamberge",
                            PhysicalAR = 158,
                            PhysicalDR = 50,
                            Stability = 35,
                            StrengthRequirement = 15,
                            StrengthScaling = "D",
                            WeaponArtId = 1,
                            Weight = 8.5
                        },
                        new
                        {
                            EquipmentId = 2,
                            AttackType = "Strike",
                            AuxEffectValue = 0,
                            AuxillaryEffectId = "N",
                            Critical = 100,
                            DarkAR = 0,
                            DarkDR = 63,
                            DexterityRequirement = 0,
                            DexterityScaling = "-",
                            Durability = 190,
                            FPConsumption = 16,
                            FaithRequirement = 0,
                            FaithScaling = "-",
                            FireAR = 0,
                            FireDR = 65,
                            FlavorText = "A greatshield adorned with flowing patterns, a celebration of an ancient glory. Boasts the highest stability of such shields, but with reduced stamina regeneration speed. Perhaps it is glory that begets such indolence.",
                            IconURL = "https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/greatshield_of_glory.png",
                            IntellectRequirement = 0,
                            IntellectScaling = "-",
                            ItemSubcategoryId = "LSh",
                            LightningAR = 0,
                            LightningDR = 52,
                            MagicAR = 0,
                            MagicDR = 70,
                            Name = "Greatshield of Glory",
                            PhysicalAR = 134,
                            PhysicalDR = 100,
                            Stability = 80,
                            StrengthRequirement = 40,
                            StrengthScaling = "D",
                            WeaponArtId = 6,
                            Weight = 18.5
                        });
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.ItemCategory", b =>
                {
                    b.Property<string>("ItemCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemCategoryId");

                    b.ToTable("ItemCategories");

                    b.HasData(
                        new
                        {
                            ItemCategoryId = "W",
                            Description = "Weapons are a type of equipment in Dark Souls 3. Players may equip up to 3 in the slots for each hand. When developing a build, the player should try to find the weapon that mixes the right amount of damage, bonuses and moveset, alongside stamina consumption and Skills. Weapon classes do not necessarily share the same skills so check each individual weapon page to see its specific skill. If you would like to learn more about each weapon, visit their page, or check out the Combat page for specific explanations on how to master the game. You can use this Equipment & Spell Checklist to keep track of what you have",
                            Name = "Weapons"
                        },
                        new
                        {
                            ItemCategoryId = "S",
                            Description = "Shields in Dark Souls 3 are an integral part of your survival as you learn the game, since even a single blow past your guard can lead to your untimely demise. More than just a wall between you and the enemy, the player is presented with a wide variety of shield styles to choose from, allowing them the freedom to integrate their shield into their own personal playstyle. With offensive applications in addition to the obvious defensive applications, shield strategy can easily become far deeper than simply blocking damage. If you'd like to see comparisons of the different shield types, please click the the link above each list.",
                            Name = "Shields"
                        },
                        new
                        {
                            ItemCategoryId = "A",
                            Description = "Armor in Dark Souls 3 provides the player with protection against damage, resistance to Status Effects, and adds Poise. Armor pieces may also be mixed and matched for cosmetic purposes. Unlike past installments in the series, armor cannot be upgraded.",
                            Name = "Armor"
                        },
                        new
                        {
                            ItemCategoryId = "R",
                            Description = @"Rings are an important category of equipment in Dark Souls 3. Players may equip up to 4 rings at once and they each grant specific benefits. This page has a list of all of the rings available in the game, separated by default and DLC rings. Click on each ring to find specific written location information. The list is by order that they will display in your inventory in game. This is to facilitate their acquisition by making it easy to see which you are missing with your inventory screen open.
A returning feature from Dark Souls 2, rings are available in more powerful iterations that appear with the + 1, +2 or + 3 suffixes.These enhanced rings are only found in NG + and beyond.Their locations and which Journey(New Game) they can be found in will be noted here and on the individual ring pages.To obtain the Trophy / Achievement fo rcollecting every ring, you must collect all of the different + X variations available, making a total of 107 rings.Do NOT sell any of the rings you've obtained.
Rings of any variation can be obtained upon each playthrough.If you miss a ring on your first playthrough, or even your second or third, you can still obtain on any following playthrough.Weather it's NG+2 or NG+20 all the rings stay where they originally are placed, they do not go away simply because you've continued playing.Meaning you can obtain the achievement on any playthrough.In addition to this information, you DO NOT need to have all the rings on you at once.Provided you have picked up the ring it counts.HOWEVER, you should always put your rings into your Item Box via the bonfire.This will allow you to keep track and KNOW for a fact what you have, I do not recommend sharing your rings amongst friends until you've gotten your achievement. 
Ring of Sacrifice DOES count towards achievement.(Got the achievement after picking up the first roS in NG++, after getting every other ring.)
116 Total Rings -9 DLC Rings(8 of which are + 3 & other is Chillbite Ring) -1(+3) Ring - 16(+2) Rings - 20(+1) Rings - 70(+0 / Regular) Rings - 107 Rings for Achievement
The Trophy / Achievement may be glitched and despite having all 107 rings in your inventory it may not register.In this case drop 15 rings, then pick them up again, then drop a different 15 and pick them up.* Do this until it registers.DO NOT drop any more than 15 to be safe.The game only allows about 30 rings to be on the ground at any time and will delete any number more than that.It's recommended that you make a backup of your save before doing this. If you chose the Life Ring as your gift at the beginning of your playthrough, you will possibly need to drop it and then pick it back up or buy another from the Handmaiden after she receives the Dreamchaser's Ashes to fix the glitched achievement.
An additional way to get around the glitch is to move a large amount of rings into your storage box and then back.This way is much safer than dropping them on the ground. ",
                            Name = "Rings"
                        },
                        new
                        {
                            ItemCategoryId = "I",
                            Description = "Items in Dark Souls 3 will be much the same as previous Souls games. Categories for the wiki are separated for player convenience into: Key Items, Multiplayer Items, Consumables, Tools, Projectiles, Ammunition, Souls, Boss Souls & Upgrade Materials.",
                            Name = "Items"
                        });
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.ItemSubcategory", b =>
                {
                    b.Property<string>("ItemSubcategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemSubcategoryId");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("ItemSubcategories");

                    b.HasData(
                        new
                        {
                            ItemSubcategoryId = "Ka",
                            Description = "Katanas are a type of Weapon in Dark Souls 3. These Weapons usually do moderate to good damage and deal Bleed. These weapons have particularly strong running attacks. Like curved swords, they're utilized primarily for slashing attacks. While useful in many scenarios, their main downfall is their low durability (an issue that is easily solved in this game, due how durability works), and really low STR scaling (gaining almost no damage benefit from using them two handed).",
                            ItemCategoryId = "W",
                            Name = "Katanas"
                        },
                        new
                        {
                            ItemSubcategoryId = "FC",
                            Description = @"Fist & Claws are a type of Weapon in Dark Souls 3. These Weapons usually have similar movesets albeit with different skills and properties. Fists and Claws are often used as parrying tools, due to their fast parry frames.
Fists:	Fist weapons have a faster light attack than Claws and a different rolling R1, but have shorter range and lack the innate Bleed Auxiliary effect that Claws have.Fist weapons are mostly used for Quality / Strength builds and due to their higher damage and considerably better Weapon Arts, they are usually favored over Claws.
Claws:	Claws have a slightly slower light attack than Fist weapons but have considerably different movesets when two handed(the Crow Talons especially).Claws have greater range than the Fists and have innate Bleed.Claws are usually used on Dexterity / Luck builds.",
                            ItemCategoryId = "W",
                            Name = "Fist & Claws"
                        },
                        new
                        {
                            ItemSubcategoryId = "Ha",
                            Description = @"Halberds are a type of Weapon in Dark Souls 3. These Weapons usually do moderate damage and have long reach. Halberds are generally either a fusion between a spear and another weapon, thus combining straight thrusting attacks and wide swinging strikes, or are simply a cutting or chopping weapon on a long shaft, which is swung across and overhead at a distance. These weapons often have trouble performing in close range or tight quarters.
Just like Reapers, they have a ""sweet spot"" mechanic that awards players extra damage. Even though the sour spots return as well, the damage difference between the sweet spot hit and the sour spot hit isn't as harsh.",
                            ItemCategoryId = "W",
                            Name = "Halberds"
                        },
                        new
                        {
                            ItemSubcategoryId = "Wh",
                            Description = "Whips are a type of Weapon in Dark Souls 3. These Weapons usually do little to moderate damage, and perform poorly against well-armored foes, but have long reach and can have Auxiliary effects such as Bleeding or Poison. Unlike other melee weapons, whips cannot be parried but cannot backstab or riposte.",
                            ItemCategoryId = "W",
                            Name = "Whips"
                        },
                        new
                        {
                            ItemSubcategoryId = "GS",
                            Description = @"Greatswords are a high damage, long reach weapon class. Plan to put a decent amount of points into Strength if you plan to use these weapons. They have various weapon Skills ranging from Stomp to Stance to unique Skills.
In terms of damage output per stamina expended, Greatswords are easily the best value weapon category, and they are a good choice for PvE builds as a result.Things to keep in mind when using these in PvP:
	 1. They have less range compared to Spears / Halberds, Greataxes, and Ultra Greatswords.
	 2. The startup to their attacks is markedly slower compared to Straight Swords, Axes, and other smaller weapons.
	 3. Despite the visual being a thrusting attack, the weapon art heavy deals standard damage(slash for the Flamberge) unless the Greatsword has a thrusting neutral heavy.",
                            ItemCategoryId = "W",
                            Name = "Greatswords"
                        },
                        new
                        {
                            ItemSubcategoryId = "SSh",
                            Description = "Small Shields  in Dark Souls 3 are a type of Shield that usually weigh very little and have the least form of protection from attacks. They are often used by players who prefer Parrying rather than Blocking.",
                            ItemCategoryId = "S",
                            Name = "Small Shields"
                        },
                        new
                        {
                            ItemSubcategoryId = "MSh",
                            Description = "Shields in Dark Souls III are an integral part of survival as you begin to understand enemy mechanics. As they are more than just a barrier used to distance yourself from imminent attacks, shields are widely avaiable in various sizes which allow a player to mesh their main-hand weapons into a personalized playstyle. With offensive applications in addition to their apparent defensive application, strategic use of the shield allows for more than simple damage reduction.",
                            ItemCategoryId = "S",
                            Name = "Standard Shields"
                        },
                        new
                        {
                            ItemSubcategoryId = "LSh",
                            Description = "Great Shields are a class of Shields in Dark Souls 3. These types of Shields usually weigh a decent amount and provide the best protection in the game. They are often used by players who have high Strength, as they require a good amount to use.",
                            ItemCategoryId = "S",
                            Name = "Greatshields"
                        });
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.WeaponArt", b =>
                {
                    b.Property<int>("WeaponArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponArtId");

                    b.ToTable("WeaponArts");

                    b.HasData(
                        new
                        {
                            WeaponArtId = 1,
                            Description = "While in stance, use normal attack to break a foe's guard from below, and strong attack to slash upwards with a forward lunge.",
                            Name = "Stance"
                        },
                        new
                        {
                            WeaponArtId = 2,
                            Description = "Cross arms in front of body to temporarily boost poise. Damage reduced while activated.",
                            Name = "Perseverance"
                        },
                        new
                        {
                            WeaponArtId = 3,
                            Description = "Spin weapon vigorously above head and sweep foes, and transition with normal or strong attack for continued spin attacks, which whip up wind and gain momentum, strengthening subsequent attacks.",
                            Name = "Wind Wheel"
                        },
                        new
                        {
                            WeaponArtId = 4,
                            Description = "Strike from the left to evade shields and deal a stinging blow that temporarily slows stamina recovery. The shackles of bondage lie deep in the hearts of all humankind.",
                            Name = "Impact"
                        },
                        new
                        {
                            WeaponArtId = 5,
                            Description = "Assume a holding stance to rapidly execute a lunging slash with normal attack, or a deflective parry with strong attack.",
                            Name = "Hold"
                        },
                        new
                        {
                            WeaponArtId = 6,
                            Description = "Without lowering your guard, strike the enemy with the shield to knock them back or stagger them. Works while equipped in either hand.",
                            Name = "Shield Bash"
                        },
                        new
                        {
                            WeaponArtId = 7,
                            Description = "Equipping this shield in the left hand allows one to perform the Skill of the right hand weapon.",
                            Name = "Weapon Skill"
                        },
                        new
                        {
                            WeaponArtId = 8,
                            Description = "Repel an attack at the right time to follow up with a critical hit.  Works while equipped in either hand.",
                            Name = "Parry"
                        },
                        new
                        {
                            WeaponArtId = 9,
                            Description = "Repel an attack at the right time to follow up with a critical hit.  Works while equipped in either hand.  Also deflects spells.",
                            Name = "Spell Parry"
                        },
                        new
                        {
                            WeaponArtId = 11,
                            Description = "Repel an attack at the right time to follow up with a critical hit.  Works while equipped in either hand.  Also deflects spells.",
                            Name = "Spell Parry"
                        });
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.Equipment", b =>
                {
                    b.HasOne("JoshuaAllison_TermProject.Models.AuxillaryEffect", "AuxEffect")
                        .WithMany()
                        .HasForeignKey("AuxillaryEffectId");

                    b.HasOne("JoshuaAllison_TermProject.Models.ItemSubcategory", "ItemSubcategory")
                        .WithMany()
                        .HasForeignKey("ItemSubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoshuaAllison_TermProject.Models.WeaponArt", "weaponArt")
                        .WithMany()
                        .HasForeignKey("WeaponArtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JoshuaAllison_TermProject.Models.ItemSubcategory", b =>
                {
                    b.HasOne("JoshuaAllison_TermProject.Models.ItemCategory", "itemCategory")
                        .WithMany()
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
